#!/bin/sh

wait_connman()
{
	while [ 1 ];
	do
	    connmanctl technologies 2>&1 | grep "was not provided" > /dev/null
	    if [ $? -ne 0 ]; then
		break
	    fi
	    sleep 5
	done
}

ap_start()
{
	wait_connman

	# reload the driver for softap mode
	modprobe -r bcm4334x
	modprobe bcm4334x op_mode=2

	# These small sleeps are unfortunate but bcm4334x driver is not able
	# to work properly without them.
	sleep 3

	connmanctl tether wifi on

	sleep 2

	# Sometimes the wlan driver is very slow to take the wlan UP,
	# so do it here (brctl will fail otherwise)
	ifconfig wlan0 up

	# FIXME: ConnMan will try to add wlan0 to tether bridge but in Edison
	# that currently fails with EBUSY. This is either wlan driver and/or
	# wpa_supplicant issue. Because of this add the wlan0 to bridge
	# manually. This is a dirty hack that will be removed when the bridging
	# works ok. JRi 8 Dec 2014
	brctl addif tether wlan0
}

ap_stop()
{
	wait_connman

	connmanctl tether wifi off

	# reload the driver for sta/p2p mode
	modprobe -r bcm4334x
	modprobe bcm4334x
}

check_status()
{
	wait_connman

	# Get the Wifi tethering status. We return 0 if tethering is not ON.
	echo `connmanctl technologies 2>&1 | \
	         sed '1,/Type = wifi/d' | \
		 grep Tethering | \
		 head -n 1 | \
		 awk '{ print $3 }'`
}

case "$1" in
start-or-stop)
	case `check_status` in
	    False) ap_stop;;
	    True) ap_start;;
	    *) exit 2;;
	esac
	;;

start)
	ap_start
	;;

stop)
	ap_stop
	;;

check)
	case `check_status` in
	    False) exit 0;;
	    True) exit 1;;
	    *) exit 2;;
	esac
	;;

toggle)
	case `check_status` in
	    False) ap_start;;
	    True) ap_stop;;
	    *) ;;
	esac
	;;

*)
	echo "Usage: $0 start|stop|check|toggle"
	echo "  start  - AP mode is started"
	echo "  stop   - AP mode is stopped and we return back to station mode"
	echo "  check  - 0 is returned if wifi tethering is currently Off"
	echo "           1 is returned if wifi tethering is currently On"
	echo "  toggle - Start or stop AP mode depending on previous mode"
	echo
	echo "This script is only usable in Edison where the Broadcom"
	echo "wifi driver firmware needs to be told which mode to operate."
	;;

esac
