# Some raspberrypi specific defaults

PREFERRED_VERSION_linux-raspberrypi_raspberrypi ?= "4.1%"
PREFERRED_VERSION_linux-raspberrypi_raspberrypi2 ?= "4.1%"

#PREFERRED_PROVIDER_virtual/bootloader_raspberrypi = "u-boot-rpi"
#PREFERRED_PROVIDER_virtual/bootloader_raspberrypi2 = "u-boot-rpi"

#KERNEL_IMAGETYPE_raspberrypi = "uImage"
#KERNEL_IMAGETYPE_raspberrypi2 = "uImage"

#IMAGE_BOOTLOADER_raspberrypi = "u-boot-rpi"
#IMAGE_BOOTLOADER_raspberrypi2 = "u-boot-rpi"
